/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TransactionsRouteImport } from './routes/transactions'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as SellRouteImport } from './routes/sell'
import { Route as SearchRouteImport } from './routes/search'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as NotificationsRouteImport } from './routes/notifications'
import { Route as MyListingsRouteImport } from './routes/my-listings'
import { Route as HelpRouteImport } from './routes/help'
import { Route as ChatsRouteImport } from './routes/chats'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AnnouncementsRouteImport } from './routes/announcements'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DisputeTransactionIdRouteImport } from './routes/dispute.$transactionId'
import { Route as ChatIdRouteImport } from './routes/chat.$id'
import { Route as ApiPublicNotifyPriceAlertsRouteImport } from './routes/api/public/notify-price-alerts'
import { Route as ApiPublicAwardReferralDiscountRouteImport } from './routes/api/public/award-referral-discount'

const TransactionsRoute = TransactionsRouteImport.update({
  id: '/transactions',
  path: '/transactions',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const SellRoute = SellRouteImport.update({
  id: '/sell',
  path: '/sell',
  getParentRoute: () => rootRouteImport,
} as any)
const SearchRoute = SearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const NotificationsRoute = NotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => rootRouteImport,
} as any)
const MyListingsRoute = MyListingsRouteImport.update({
  id: '/my-listings',
  path: '/my-listings',
  getParentRoute: () => rootRouteImport,
} as any)
const HelpRoute = HelpRouteImport.update({
  id: '/help',
  path: '/help',
  getParentRoute: () => rootRouteImport,
} as any)
const ChatsRoute = ChatsRouteImport.update({
  id: '/chats',
  path: '/chats',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AnnouncementsRoute = AnnouncementsRouteImport.update({
  id: '/announcements',
  path: '/announcements',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DisputeTransactionIdRoute = DisputeTransactionIdRouteImport.update({
  id: '/dispute/$transactionId',
  path: '/dispute/$transactionId',
  getParentRoute: () => rootRouteImport,
} as any)
const ChatIdRoute = ChatIdRouteImport.update({
  id: '/chat/$id',
  path: '/chat/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicNotifyPriceAlertsRoute =
  ApiPublicNotifyPriceAlertsRouteImport.update({
    id: '/api/public/notify-price-alerts',
    path: '/api/public/notify-price-alerts',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicAwardReferralDiscountRoute =
  ApiPublicAwardReferralDiscountRouteImport.update({
    id: '/api/public/award-referral-discount',
    path: '/api/public/award-referral-discount',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/announcements': typeof AnnouncementsRoute
  '/auth': typeof AuthRoute
  '/chats': typeof ChatsRoute
  '/help': typeof HelpRoute
  '/my-listings': typeof MyListingsRoute
  '/notifications': typeof NotificationsRoute
  '/privacy': typeof PrivacyRoute
  '/profile': typeof ProfileRoute
  '/reset-password': typeof ResetPasswordRoute
  '/search': typeof SearchRoute
  '/sell': typeof SellRoute
  '/terms': typeof TermsRoute
  '/transactions': typeof TransactionsRoute
  '/chat/$id': typeof ChatIdRoute
  '/dispute/$transactionId': typeof DisputeTransactionIdRoute
  '/api/public/award-referral-discount': typeof ApiPublicAwardReferralDiscountRoute
  '/api/public/notify-price-alerts': typeof ApiPublicNotifyPriceAlertsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/announcements': typeof AnnouncementsRoute
  '/auth': typeof AuthRoute
  '/chats': typeof ChatsRoute
  '/help': typeof HelpRoute
  '/my-listings': typeof MyListingsRoute
  '/notifications': typeof NotificationsRoute
  '/privacy': typeof PrivacyRoute
  '/profile': typeof ProfileRoute
  '/reset-password': typeof ResetPasswordRoute
  '/search': typeof SearchRoute
  '/sell': typeof SellRoute
  '/terms': typeof TermsRoute
  '/transactions': typeof TransactionsRoute
  '/chat/$id': typeof ChatIdRoute
  '/dispute/$transactionId': typeof DisputeTransactionIdRoute
  '/api/public/award-referral-discount': typeof ApiPublicAwardReferralDiscountRoute
  '/api/public/notify-price-alerts': typeof ApiPublicNotifyPriceAlertsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/announcements': typeof AnnouncementsRoute
  '/auth': typeof AuthRoute
  '/chats': typeof ChatsRoute
  '/help': typeof HelpRoute
  '/my-listings': typeof MyListingsRoute
  '/notifications': typeof NotificationsRoute
  '/privacy': typeof PrivacyRoute
  '/profile': typeof ProfileRoute
  '/reset-password': typeof ResetPasswordRoute
  '/search': typeof SearchRoute
  '/sell': typeof SellRoute
  '/terms': typeof TermsRoute
  '/transactions': typeof TransactionsRoute
  '/chat/$id': typeof ChatIdRoute
  '/dispute/$transactionId': typeof DisputeTransactionIdRoute
  '/api/public/award-referral-discount': typeof ApiPublicAwardReferralDiscountRoute
  '/api/public/notify-price-alerts': typeof ApiPublicNotifyPriceAlertsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/announcements'
    | '/auth'
    | '/chats'
    | '/help'
    | '/my-listings'
    | '/notifications'
    | '/privacy'
    | '/profile'
    | '/reset-password'
    | '/search'
    | '/sell'
    | '/terms'
    | '/transactions'
    | '/chat/$id'
    | '/dispute/$transactionId'
    | '/api/public/award-referral-discount'
    | '/api/public/notify-price-alerts'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/announcements'
    | '/auth'
    | '/chats'
    | '/help'
    | '/my-listings'
    | '/notifications'
    | '/privacy'
    | '/profile'
    | '/reset-password'
    | '/search'
    | '/sell'
    | '/terms'
    | '/transactions'
    | '/chat/$id'
    | '/dispute/$transactionId'
    | '/api/public/award-referral-discount'
    | '/api/public/notify-price-alerts'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/announcements'
    | '/auth'
    | '/chats'
    | '/help'
    | '/my-listings'
    | '/notifications'
    | '/privacy'
    | '/profile'
    | '/reset-password'
    | '/search'
    | '/sell'
    | '/terms'
    | '/transactions'
    | '/chat/$id'
    | '/dispute/$transactionId'
    | '/api/public/award-referral-discount'
    | '/api/public/notify-price-alerts'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRoute
  AnnouncementsRoute: typeof AnnouncementsRoute
  AuthRoute: typeof AuthRoute
  ChatsRoute: typeof ChatsRoute
  HelpRoute: typeof HelpRoute
  MyListingsRoute: typeof MyListingsRoute
  NotificationsRoute: typeof NotificationsRoute
  PrivacyRoute: typeof PrivacyRoute
  ProfileRoute: typeof ProfileRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  SearchRoute: typeof SearchRoute
  SellRoute: typeof SellRoute
  TermsRoute: typeof TermsRoute
  TransactionsRoute: typeof TransactionsRoute
  ChatIdRoute: typeof ChatIdRoute
  DisputeTransactionIdRoute: typeof DisputeTransactionIdRoute
  ApiPublicAwardReferralDiscountRoute: typeof ApiPublicAwardReferralDiscountRoute
  ApiPublicNotifyPriceAlertsRoute: typeof ApiPublicNotifyPriceAlertsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/transactions': { id: '/transactions'; path: '/transactions'; fullPath: '/transactions'; preLoaderRoute: typeof TransactionsRouteImport; parentRoute: typeof rootRouteImport }
    '/terms': { id: '/terms'; path: '/terms'; fullPath: '/terms'; preLoaderRoute: typeof TermsRouteImport; parentRoute: typeof rootRouteImport }
    '/sell': { id: '/sell'; path: '/sell'; fullPath: '/sell'; preLoaderRoute: typeof SellRouteImport; parentRoute: typeof rootRouteImport }
    '/search': { id: '/search'; path: '/search'; fullPath: '/search'; preLoaderRoute: typeof SearchRouteImport; parentRoute: typeof rootRouteImport }
    '/reset-password': { id: '/reset-password'; path: '/reset-password'; fullPath: '/reset-password'; preLoaderRoute: typeof ResetPasswordRouteImport; parentRoute: typeof rootRouteImport }
    '/profile': { id: '/profile'; path: '/profile'; fullPath: '/profile'; preLoaderRoute: typeof ProfileRouteImport; parentRoute: typeof rootRouteImport }
    '/privacy': { id: '/privacy'; path: '/privacy'; fullPath: '/privacy'; preLoaderRoute: typeof PrivacyRouteImport; parentRoute: typeof rootRouteImport }
    '/notifications': { id: '/notifications'; path: '/notifications'; fullPath: '/notifications'; preLoaderRoute: typeof NotificationsRouteImport; parentRoute: typeof rootRouteImport }
    '/my-listings': { id: '/my-listings'; path: '/my-listings'; fullPath: '/my-listings'; preLoaderRoute: typeof MyListingsRouteImport; parentRoute: typeof rootRouteImport }
    '/help': { id: '/help'; path: '/help'; fullPath: '/help'; preLoaderRoute: typeof HelpRouteImport; parentRoute: typeof rootRouteImport }
    '/chats': { id: '/chats'; path: '/chats'; fullPath: '/chats'; preLoaderRoute: typeof ChatsRouteImport; parentRoute: typeof rootRouteImport }
    '/auth': { id: '/auth'; path: '/auth'; fullPath: '/auth'; preLoaderRoute: typeof AuthRouteImport; parentRoute: typeof rootRouteImport }
    '/announcements': { id: '/announcements'; path: '/announcements'; fullPath: '/announcements'; preLoaderRoute: typeof AnnouncementsRouteImport; parentRoute: typeof rootRouteImport }
    '/admin': { id: '/admin'; path: '/admin'; fullPath: '/admin'; preLoaderRoute: typeof AdminRouteImport; parentRoute: typeof rootRouteImport }
    '/': { id: '/'; path: '/'; fullPath: '/'; preLoaderRoute: typeof IndexRouteImport; parentRoute: typeof rootRouteImport }
    '/dispute/$transactionId': { id: '/dispute/$transactionId'; path: '/dispute/$transactionId'; fullPath: '/dispute/$transactionId'; preLoaderRoute: typeof DisputeTransactionIdRouteImport; parentRoute: typeof rootRouteImport }
    '/chat/$id': { id: '/chat/$id'; path: '/chat/$id'; fullPath: '/chat/$id'; preLoaderRoute: typeof ChatIdRouteImport; parentRoute: typeof rootRouteImport }
    '/api/public/notify-price-alerts': { id: '/api/public/notify-price-alerts'; path: '/api/public/notify-price-alerts'; fullPath: '/api/public/notify-price-alerts'; preLoaderRoute: typeof ApiPublicNotifyPriceAlertsRouteImport; parentRoute: typeof rootRouteImport }
    '/api/public/award-referral-discount': { id: '/api/public/award-referral-discount'; path: '/api/public/award-referral-discount'; fullPath: '/api/public/award-referral-discount'; preLoaderRoute: typeof ApiPublicAwardReferralDiscountRouteImport; parentRoute: typeof rootRouteImport }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRoute,
  AnnouncementsRoute: AnnouncementsRoute,
  AuthRoute: AuthRoute,
  ChatsRoute: ChatsRoute,
  HelpRoute: HelpRoute,
  MyListingsRoute: MyListingsRoute,
  NotificationsRoute: NotificationsRoute,
  PrivacyRoute: PrivacyRoute,
  ProfileRoute: ProfileRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  SearchRoute: SearchRoute,
  SellRoute: SellRoute,
  TermsRoute: TermsRoute,
  TransactionsRoute: TransactionsRoute,
  ChatIdRoute: ChatIdRoute,
  DisputeTransactionIdRoute: DisputeTransactionIdRoute,
  ApiPublicAwardReferralDiscountRoute: ApiPublicAwardReferralDiscountRoute,
  ApiPublicNotifyPriceAlertsRoute: ApiPublicNotifyPriceAlertsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
